# model
model_name_or_path: baichuan-inc/Baichuan2-7B-Base

# method
finetuning_type: lora

# dataset
task: ceval
split: test
template: fewshot
lang: zh
n_shot: 0

# output
save_dir: saves/urban/baichuan2_base

# eval
batch_size: 4
