# model
model_name_or_path: ZhipuAI/chatglm3-6b
#adapter_name_or_path: saves/ChatGLM3-6B-Chat/lora/train_2024-05-07-15-29-18

# method
finetuning_type: lora

# dataset
task: ceval
split: test
template: fewshot
lang: zh
n_shot: 0

# output
save_dir: saves/urban/glm3_6b_chat

# eval
batch_size: 4
