# model
model_name_or_path: ZhipuAI/chatglm3-6b-base
adapter_name_or_path: saves/ChatGLM3-6B-Base/lora/train_2024-05-12-11-49-05

# method
finetuning_type: lora

# dataset
task: cevalm
split: test
template: fewshot
lang: zh-m
n_shot: 0

# output
save_dir: saves/urban/planglm3_base_m_epoch100

# eval
batch_size: 4
